// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_too_stubborn_to_quit = "CgkIsrqqqssOEAIQCA"; // <GPGSID>
        public const string achievement_behind_cover = "CgkIsrqqqssOEAIQCw"; // <GPGSID>
        public const string achievement_echo_initiate = "CgkIsrqqqssOEAIQAw"; // <GPGSID>
        public const string achievement_treasure_hunter = "CgkIsrqqqssOEAIQJA"; // <GPGSID>
        public const string achievement_reaper = "CgkIsrqqqssOEAIQBg"; // <GPGSID>
        public const string achievement_magnetic_attraction = "CgkIsrqqqssOEAIQCQ"; // <GPGSID>
        public const string achievement_fate_defied = "CgkIsrqqqssOEAIQDA"; // <GPGSID>
        public const string achievement_no_turning_back = "CgkIsrqqqssOEAIQAg"; // <GPGSID>
        public const string achievement_pocket_change = "CgkIsrqqqssOEAIQFg"; // <GPGSID>
        public const string achievement_close_call = "CgkIsrqqqssOEAIQGQ"; // <GPGSID>
        public const string achievement_fortune_favors_the_fast = "CgkIsrqqqssOEAIQFA"; // <GPGSID>
        public const string achievement_still_standing = "CgkIsrqqqssOEAIQBQ"; // <GPGSID>
        public const string achievement_dark_fate = "CgkIsrqqqssOEAIQDg"; // <GPGSID>
        public const string achievement_burned_once = "CgkIsrqqqssOEAIQEg"; // <GPGSID>
        public const string achievement_double_trouble = "CgkIsrqqqssOEAIQDw"; // <GPGSID>
        public const string achievement_warming_up = "CgkIsrqqqssOEAIQBA"; // <GPGSID>
        public const string achievement_quick_reflexes = "CgkIsrqqqssOEAIQHw"; // <GPGSID>
        public const string achievement_light_show_casualty = "CgkIsrqqqssOEAIQJg"; // <GPGSID>
        public const string achievement_payback = "CgkIsrqqqssOEAIQGA"; // <GPGSID>
        public const string achievement_shadow_army = "CgkIsrqqqssOEAIQJQ"; // <GPGSID>
        public const string achievement_first_contact = "CgkIsrqqqssOEAIQHg"; // <GPGSID>
        public const string achievement_combo_master = "CgkIsrqqqssOEAIQCg"; // <GPGSID>
        public const string achievement_golden_fate = "CgkIsrqqqssOEAIQHQ"; // <GPGSID>
        public const string achievement_master_of_time = "CgkIsrqqqssOEAIQKA"; // <GPGSID>
        public const string achievement_untouchable = "CgkIsrqqqssOEAIQIw"; // <GPGSID>
        public const string achievement_laserproof = "CgkIsrqqqssOEAIQEw"; // <GPGSID>
        public const string achievement_bomb_magnet = "CgkIsrqqqssOEAIQIQ"; // <GPGSID>
        public const string achievement_counterattack = "CgkIsrqqqssOEAIQAQ"; // <GPGSID>
        public const string achievement_bad_step = "CgkIsrqqqssOEAIQFw"; // <GPGSID>
        public const string achievement_iron_resolve = "CgkIsrqqqssOEAIQDQ"; // <GPGSID>
        public const string achievement_thread_the_needle = "CgkIsrqqqssOEAIQGg"; // <GPGSID>
        public const string achievement_born_to_rush = "CgkIsrqqqssOEAIQIg"; // <GPGSID>
        public const string achievement_first_rush = "CgkIsrqqqssOEAIQJw"; // <GPGSID>
        public const string achievement_ground_zero = "CgkIsrqqqssOEAIQEA"; // <GPGSID>
        public const string achievement_blink_and_you_miss_me = "CgkIsrqqqssOEAIQHA"; // <GPGSID>
        public const string achievement_halfway_there = "CgkIsrqqqssOEAIQGw"; // <GPGSID>
        public const string achievement_divide_and_conquer = "CgkIsrqqqssOEAIQFQ"; // <GPGSID>
        public const string achievement_time_bender = "CgkIsrqqqssOEAIQEQ"; // <GPGSID>
        public const string achievement_living_on_the_edge = "CgkIsrqqqssOEAIQIA"; // <GPGSID>
        public const string achievement_suit_up = "CgkIsrqqqssOEAIQBw"; // <GPGSID>

}

